"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

########################################################
# * General settings
# ! Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
########################################################

BASE_DIR = Path(__file__).resolve().parent.parent

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]
ROOT_URLCONF = "dev.urls"
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#! SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-3z_2g)bez2*jqk4-%zm&06t+xjud(wjgii4s*x(9)7468qbyo1"

#! SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
TESTING = "test" in sys.argv or "PYTEST_VERSION" in os.environ

WSGI_APPLICATION = "dev.wsgi.application"

# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"

########################################################
# * CORS settings for dev server
#
########################################################
CORS_ORIGIN_ALLOW_ALL = True

########################################################
# * Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
########################################################

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

########################################################
# * Apps
########################################################

INSTALLED_APPS = [
    # Django unfold admin panel https://unfoldadmin.com/docs/
    "unfold",  # before django.contrib.admin
    # Django core apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "corsheaders",  # https://pypi.org/project/django-cors-headers/
    # * Local apps
    "django_cap",
    "django_cap.ninja_api",
]

if DEBUG and not TESTING:
    INSTALLED_APPS += [
        "debug_toolbar",  # https://django-debug-toolbar.readthedocs.io/
    ]

########################################################
# * django_cap settings
########################################################
CAP_NINJA_API_ENABLE_DOCS = True

########################################################
# * Middleware
########################################################

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if DEBUG and not TESTING:
    MIDDLEWARE += [
        "debug_toolbar.middleware.DebugToolbarMiddleware",  # https://django-debug-toolbar.readthedocs.io/
    ]

INTERNAL_IPS = [
    "127.0.0.1",
    "localhost",
]

########################################################
# * Templates
########################################################

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.request",
            ],
        },
    },
]

########################################################
# * Database Settings
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
########################################################

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.dev.sqlite3",
    }
}

########################################################
# * Authentication and Authorizations
########################################################

AUTH_PASSWORD_VALIDATORS = [
    # Password validation
    # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = ("django.contrib.auth.backends.ModelBackend",)

########################################################
# * Unfold Admin settings
########################################################

UNFOLD = {
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
    },
}

########################################################
# * Django Ninja settings
########################################################
